services:
  db:
    image: postgres:12
    restart: always
    container_name: db
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=visby
      - POSTGRES_SERVER=localhost
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    networks:
      - visby-network
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
  
  db-init:
    build:
      context: .
      dockerfile: ./docker/ci.dockerfile
    command: alembic upgrade head
    environment:
      - VISBY_DATABASE_URL=postgresql://postgres:postgres@db:5432/visby
    networks:
      - visby-network
    depends_on:
      db:
        condition: service_healthy

  visby-app:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    restart: always
    environment:
      - PORT=8000
      - POSTGRES_DATABASE_URL=postgresql://postgres:postgres@db:5432/visby
    ports:
      - "8000:8000"
    networks:
      - visby-network

volumes:
  db-data:

networks:
  visby-network:
    driver: bridge
